### PR TITLE
Replace `<` with `isless`

### LINKED ISSUE #19: Missing `isless` means that `sort` fails
...unless you specify `lt=<`.

### PR DESCRIPTION
**Pull request by spurll**
Allows `sort`ing of `AbstractInterval`s.

Closes #19

### CODE REVIEW

File: test/anchoredinterval.jl [hunk 1]
```diff
@@ -346,6 +350,16 @@ using Intervals: canonicalize
...
     end
 
+    @testset "sort" begin
+        hb1 = HourBeginning(dt)
+        he1 = HourEnding(dt)
+        he2 = HourEnding(dt + Hour(1))
+        he3 = HourEnding(dt + Hour(2))
+
+        @test sort([hb1, he1, he2, he3]) == [he1, hb1, he2, he3]
+        @test sort([hb1, he1, he2, he3]; rev=true) == [he3, he2, hb1, he1]
```
Comment (omus) [inline test/anchoredinterval.jl]: Doesn't honestly matter but these could be `sort!`
