### PR TITLE
Replace `in` with `issubset`

### LINKED ISSUE #15: Replace `in(::AbstractInterval, ::AbstractInterval)` with `issubset(::AbstractInterval, ::AbstractInterval)`
Because `in` is the wrong function to use in this case.

### PR DESCRIPTION
**Pull request by spurll**
Replace `in(::AbstractInterval, ::AbstractInterval)` with `issubset(::AbstractInterval, ::AbstractInterval)` and define/export `⊆`, `⊇`, `⊈`, and `⊉`

Closes #15

### CODE REVIEW

File: src/interval.jl [hunk 1]
```diff
@@ -1,3 +1,5 @@
+
+
```
Comment (omus) [inline src/interval.jl]: On purpose?
